apiVersion: v1
kind: ServiceAccount
metadata:
  name: sre-crew-sa
  namespace: sre-crew
---
# Change Kind from Role -> ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sre-crew-cluster-role
rules:
# Allow managing StatefulSets & Deployments in ANY namespace
- apiGroups: ["apps"]
  resources: ["statefulsets", "statefulsets/scale", "deployments", "deployments/scale"]
  verbs: ["get", "list", "patch", "update"]
# Allow reading Pods/Nodes (for general monitoring)
- apiGroups: [""]
  resources: ["pods", "nodes", "configmaps", "services"]
  verbs: ["get", "list"]
---
# Change Kind from RoleBinding -> ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sre-crew-global-binding
subjects:
- kind: ServiceAccount
  name: sre-crew-sa
  # IMPORTANT: We must specify where the ServiceAccount lives
  namespace: sre-crew
roleRef:
  kind: ClusterRole
  name: sre-crew-cluster-role
  apiGroup: rbac.authorization.k8s.io
