apiVersion: v1
kind: ServiceAccount
metadata:
  name: sre-crew-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sre-crew-role
rules:
- apiGroups: ["apps", "extensions"]
  resources: ["deployments"]
  verbs: ["get", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sre-crew-binding
subjects:
- kind: ServiceAccount
  name: sre-crew-sa
roleRef:
  kind: Role
  name: sre-crew-role
  apiGroup: rbac.authorization.k8s.io
